import requests
import pandas as pd
from io import StringIO
from pathlib import Path


PROJECT_DIR = Path(__file__).parent
OUTPUT_FILE = PROJECT_DIR / "sp500_ciks.py"


def normalize_ticker(ticker: str) -> str:
    return ticker.replace(".", "-").upper()


def build_sp500_ciks() -> dict:
    url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"

    headers = {
        "User-Agent": "Follow_the_money" "velasus99@gmail.com",
        "Accept": "text/html",
    }

    response = requests.get(url, headers=headers, timeout=30)
    response.raise_for_status()

    tables = pd.read_html(StringIO(response.text))
    sp500 = tables[0]

    ciks = {}

    for _, row in sp500.iterrows():
        ticker = normalize_ticker(row["Symbol"])
        cik = str(row["CIK"]).zfill(10)
        ciks[ticker] = cik

    return ciks


def write_ciks_module(ciks: dict):
    with open(OUTPUT_FILE, "w", encoding="utf-8") as file:
        file.write("# Auto-generated by build_sp500_ciks.py\n")
        file.write("# Do not edit manually unless necessary.\n\n")
        file.write("CIKS_SP500_ALL = {\n")

        for ticker, cik in ciks.items():
            file.write(f'    "{ticker}": "{cik}",\n')

        file.write("}\n")


if __name__ == "__main__":
    ciks = build_sp500_ciks()
    write_ciks_module(ciks)

    print(f"Wrote {len(ciks)} tickers to {OUTPUT_FILE}")



